

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient} from '@angular/common/http'; 
import { Observable } from 'rxjs';

import { PersonDto } from '../Entities/PersonDto';import { LoginCredentialsDto } from '../Entities/LoginCredentialsDto';
@Injectable()
export class AccountController {
    constructor(private _httpClient: HttpClient) { }        
    
    // get: /api/account/getAccount      
    get(): Observable<PersonDto> {
        var _Url = `/api/account/getAccount`;
            return this._httpClient.get<PersonDto>(_Url);
    }
    
    // post: /api/account?userName=${encodeURIComponent(userName)}      
    create(userName: string): Observable<void> {
        var _Url = `/api/account?userName=${encodeURIComponent(userName)}`;
            return this._httpClient.post<void>(_Url,userName);
    }
    
    // post: /api/account/login      
    login(credentials: LoginCredentialsDto): Observable<void> {
        var _Url = `/api/account/login`;
            return this._httpClient.post<void>(_Url,credentials);
    }
    
}
